import {
  SignedIn,
  SignedOut,
  SignInWithMetamaskButton,
} from "@clerk/clerk-react";
import Head from "next/head";
import User from "../components/User";

export default function Home() {
  return (
    <div className="flex justify-center mt-80">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <SignedOut>
        <SignInWithMetamaskButton>
          Sign in with Metamask
        </SignInWithMetamaskButton>
      </SignedOut>
      <SignedIn>
        <User />
      </SignedIn>
    </div>
  );
}
